name: PaperBot

on:
  #schedule: cron "*/5 * * * *" (there was smth like this, but it was disabled, because it is no longer needed to work like this/that)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install slack_sdk

      - name: Run Python bot
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: python bot.py
